### ISSUE TITLE
installing and running

### ISSUE THREAD

**Issue by grenaud** [PierreBarrat/AncestralSequenceReconstruction.jl#2]
I just saw your pre-print, interesting stuff! Could you please provide instructions how to build the software and run it?

**Comment by PierreBarrat** [comment]
Thank you for your interest. I'll write a brief start-up guide to the software in the next days!

**Comment by PierreBarrat** [comment]
@grenaud  I wrote a README with instructions on how to install and run an example notebook, as well as other information. Please tell me if you run into issues when trying this out.

**Comment by grenaud** [comment]
Thanks a lot! I'm a bit too swamped now to check it out but I will come back to this :-)
